//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Final_Senior_DBEntities1 : DbContext
    {
        public Final_Senior_DBEntities1()
            : base("name=Final_Senior_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameFrame> GameFrames { get; set; }
        public virtual DbSet<GFStrategy> GFStrategies { get; set; }
        public virtual DbSet<NashPointProfile> NashPointProfiles { get; set; }
        public virtual DbSet<NPPayoff> NPPayoffs { get; set; }
        public virtual DbSet<NPStrategy> NPStrategies { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
