//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorServer.SeniorDBServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SeniorDBServiceRef.IDBFunctions")]
    public interface IDBFunctions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGameFrame", ReplyAction="http://tempuri.org/IDBFunctions/AddGameFrameResponse")]
        int AddGameFrame(SeniorDBServer.GameFrameModel gf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGameFrame", ReplyAction="http://tempuri.org/IDBFunctions/AddGameFrameResponse")]
        System.Threading.Tasks.Task<int> AddGameFrameAsync(SeniorDBServer.GameFrameModel gf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/DeleteGameFrame", ReplyAction="http://tempuri.org/IDBFunctions/DeleteGameFrameResponse")]
        int DeleteGameFrame(string T);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/DeleteGameFrame", ReplyAction="http://tempuri.org/IDBFunctions/DeleteGameFrameResponse")]
        System.Threading.Tasks.Task<int> DeleteGameFrameAsync(string T);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGameFrame", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGameFrameResponse")]
        SeniorDBServer.GameFrameModel RetreiveGameFrame(string T);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGameFrame", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGameFrameResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GameFrameModel> RetreiveGameFrameAsync(string T);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMinPlayers", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMinPlayersResponse")]
        int UpdateGameFrameMinPlayers(string title, int min);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMinPlayers", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMinPlayersResponse")]
        System.Threading.Tasks.Task<int> UpdateGameFrameMinPlayersAsync(string title, int min);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxPlayers", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxPlayersResponse")]
        int UpdateGameFrameMaxPlayers(string title, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxPlayers", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxPlayersResponse")]
        System.Threading.Tasks.Task<int> UpdateGameFrameMaxPlayersAsync(string title, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMinStrategies", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMinStrategiesResponse")]
        int UpdateGameFrameMinStrategies(string title, int min);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMinStrategies", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMinStrategiesResponse")]
        System.Threading.Tasks.Task<int> UpdateGameFrameMinStrategiesAsync(string title, int min);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxStrategies", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxStrategiesResponse")]
        int UpdateGameFrameMaxStrategies(string title, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxStrategies", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameFrameMaxStrategiesResponse")]
        System.Threading.Tasks.Task<int> UpdateGameFrameMaxStrategiesAsync(string title, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveAllGameFrames", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveAllGameFramesResponse")]
        SeniorDBServer.GameFrameModel[] RetreiveAllGameFrames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveAllGameFrames", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveAllGameFramesResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GameFrameModel[]> RetreiveAllGameFramesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddUser", ReplyAction="http://tempuri.org/IDBFunctions/AddUserResponse")]
        int AddUser(SeniorDBServer.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddUser", ReplyAction="http://tempuri.org/IDBFunctions/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(SeniorDBServer.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveUser", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveUserResponse")]
        SeniorDBServer.UserModel RetreiveUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveUser", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveUserResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.UserModel> RetreiveUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateUser", ReplyAction="http://tempuri.org/IDBFunctions/UpdateUserResponse")]
        int UpdateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateUser", ReplyAction="http://tempuri.org/IDBFunctions/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGamePlayer", ReplyAction="http://tempuri.org/IDBFunctions/AddGamePlayerResponse")]
        int AddGamePlayer(SeniorDBServer.GamePlayerModel player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGamePlayer", ReplyAction="http://tempuri.org/IDBFunctions/AddGamePlayerResponse")]
        System.Threading.Tasks.Task<int> AddGamePlayerAsync(SeniorDBServer.GamePlayerModel player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGamePlayers", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGamePlayersResponse")]
        SeniorDBServer.GamePlayerModel[] RetreiveGamePlayers(int gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGamePlayers", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGamePlayersResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GamePlayerModel[]> RetreiveGamePlayersAsync(int gid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreivePlayerGames", ReplyAction="http://tempuri.org/IDBFunctions/RetreivePlayerGamesResponse")]
        int[] RetreivePlayerGames(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreivePlayerGames", ReplyAction="http://tempuri.org/IDBFunctions/RetreivePlayerGamesResponse")]
        System.Threading.Tasks.Task<int[]> RetreivePlayerGamesAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGame", ReplyAction="http://tempuri.org/IDBFunctions/AddGameResponse")]
        int AddGame(SeniorDBServer.GameModel game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGame", ReplyAction="http://tempuri.org/IDBFunctions/AddGameResponse")]
        System.Threading.Tasks.Task<int> AddGameAsync(SeniorDBServer.GameModel game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/DeleteGame", ReplyAction="http://tempuri.org/IDBFunctions/DeleteGameResponse")]
        int DeleteGame(int gameid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/DeleteGame", ReplyAction="http://tempuri.org/IDBFunctions/DeleteGameResponse")]
        System.Threading.Tasks.Task<int> DeleteGameAsync(int gameid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGame", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGameResponse")]
        SeniorDBServer.GameModel RetreiveGame(int gameid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGame", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGameResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GameModel> RetreiveGameAsync(int gameid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveAllGames", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveAllGamesResponse")]
        SeniorDBServer.GameModel[] RetreiveAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveAllGames", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveAllGamesResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GameModel[]> RetreiveAllGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameNumofPlayers", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameNumofPlayersResponse")]
        int UpdateGameNumofPlayers(int gid, int nop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/UpdateGameNumofPlayers", ReplyAction="http://tempuri.org/IDBFunctions/UpdateGameNumofPlayersResponse")]
        System.Threading.Tasks.Task<int> UpdateGameNumofPlayersAsync(int gid, int nop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/GameByNumPlayer", ReplyAction="http://tempuri.org/IDBFunctions/GameByNumPlayerResponse")]
        SeniorDBServer.GameFrameModel[] GameByNumPlayer(int nop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/GameByNumPlayer", ReplyAction="http://tempuri.org/IDBFunctions/GameByNumPlayerResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GameFrameModel[]> GameByNumPlayerAsync(int nop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGFStrategy", ReplyAction="http://tempuri.org/IDBFunctions/AddGFStrategyResponse")]
        int AddGFStrategy(SeniorDBServer.GFStrategyModel gfstrategy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddGFStrategy", ReplyAction="http://tempuri.org/IDBFunctions/AddGFStrategyResponse")]
        System.Threading.Tasks.Task<int> AddGFStrategyAsync(SeniorDBServer.GFStrategyModel gfstrategy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGFStrategy", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGFStrategyResponse")]
        SeniorDBServer.GFStrategyModel RetreiveGFStrategy(int gfstrategyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveGFStrategy", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveGFStrategyResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.GFStrategyModel> RetreiveGFStrategyAsync(int gfstrategyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddNPStrategy", ReplyAction="http://tempuri.org/IDBFunctions/AddNPStrategyResponse")]
        int AddNPStrategy(SeniorDBServer.NPStrategyModel npstrategy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddNPStrategy", ReplyAction="http://tempuri.org/IDBFunctions/AddNPStrategyResponse")]
        System.Threading.Tasks.Task<int> AddNPStrategyAsync(SeniorDBServer.NPStrategyModel npstrategy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveNPStrategy", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveNPStrategyResponse")]
        SeniorDBServer.NPStrategyModel RetreiveNPStrategy(int npstrategyid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveNPStrategy", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveNPStrategyResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.NPStrategyModel> RetreiveNPStrategyAsync(int npstrategyid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddNashPointProfile", ReplyAction="http://tempuri.org/IDBFunctions/AddNashPointProfileResponse")]
        int AddNashPointProfile(SeniorDBServer.NashPointProfileModel NP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddNashPointProfile", ReplyAction="http://tempuri.org/IDBFunctions/AddNashPointProfileResponse")]
        System.Threading.Tasks.Task<int> AddNashPointProfileAsync(SeniorDBServer.NashPointProfileModel NP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveNashPointProfile", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveNashPointProfileResponse")]
        SeniorDBServer.NashPointProfileModel RetreiveNashPointProfile(int NPID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveNashPointProfile", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveNashPointProfileResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.NashPointProfileModel> RetreiveNashPointProfileAsync(int NPID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddNPPayoff", ReplyAction="http://tempuri.org/IDBFunctions/AddNPPayoffResponse")]
        int AddNPPayoff(SeniorDBServer.NPPayoffModel payoff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/AddNPPayoff", ReplyAction="http://tempuri.org/IDBFunctions/AddNPPayoffResponse")]
        System.Threading.Tasks.Task<int> AddNPPayoffAsync(SeniorDBServer.NPPayoffModel payoff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveNPPayoff", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveNPPayoffResponse")]
        SeniorDBServer.NPPayoffModel RetreiveNPPayoff(int payoffid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBFunctions/RetreiveNPPayoff", ReplyAction="http://tempuri.org/IDBFunctions/RetreiveNPPayoffResponse")]
        System.Threading.Tasks.Task<SeniorDBServer.NPPayoffModel> RetreiveNPPayoffAsync(int payoffid, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBFunctionsChannel : SeniorServer.SeniorDBServiceRef.IDBFunctions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBFunctionsClient : System.ServiceModel.ClientBase<SeniorServer.SeniorDBServiceRef.IDBFunctions>, SeniorServer.SeniorDBServiceRef.IDBFunctions {
        
        public DBFunctionsClient() {
        }
        
        public DBFunctionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBFunctionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBFunctionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBFunctionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddGameFrame(SeniorDBServer.GameFrameModel gf) {
            return base.Channel.AddGameFrame(gf);
        }
        
        public System.Threading.Tasks.Task<int> AddGameFrameAsync(SeniorDBServer.GameFrameModel gf) {
            return base.Channel.AddGameFrameAsync(gf);
        }
        
        public int DeleteGameFrame(string T) {
            return base.Channel.DeleteGameFrame(T);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGameFrameAsync(string T) {
            return base.Channel.DeleteGameFrameAsync(T);
        }
        
        public SeniorDBServer.GameFrameModel RetreiveGameFrame(string T) {
            return base.Channel.RetreiveGameFrame(T);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GameFrameModel> RetreiveGameFrameAsync(string T) {
            return base.Channel.RetreiveGameFrameAsync(T);
        }
        
        public int UpdateGameFrameMinPlayers(string title, int min) {
            return base.Channel.UpdateGameFrameMinPlayers(title, min);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameFrameMinPlayersAsync(string title, int min) {
            return base.Channel.UpdateGameFrameMinPlayersAsync(title, min);
        }
        
        public int UpdateGameFrameMaxPlayers(string title, int max) {
            return base.Channel.UpdateGameFrameMaxPlayers(title, max);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameFrameMaxPlayersAsync(string title, int max) {
            return base.Channel.UpdateGameFrameMaxPlayersAsync(title, max);
        }
        
        public int UpdateGameFrameMinStrategies(string title, int min) {
            return base.Channel.UpdateGameFrameMinStrategies(title, min);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameFrameMinStrategiesAsync(string title, int min) {
            return base.Channel.UpdateGameFrameMinStrategiesAsync(title, min);
        }
        
        public int UpdateGameFrameMaxStrategies(string title, int max) {
            return base.Channel.UpdateGameFrameMaxStrategies(title, max);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameFrameMaxStrategiesAsync(string title, int max) {
            return base.Channel.UpdateGameFrameMaxStrategiesAsync(title, max);
        }
        
        public SeniorDBServer.GameFrameModel[] RetreiveAllGameFrames() {
            return base.Channel.RetreiveAllGameFrames();
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GameFrameModel[]> RetreiveAllGameFramesAsync() {
            return base.Channel.RetreiveAllGameFramesAsync();
        }
        
        public int AddUser(SeniorDBServer.UserModel user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(SeniorDBServer.UserModel user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public SeniorDBServer.UserModel RetreiveUser(string username, string password) {
            return base.Channel.RetreiveUser(username, password);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.UserModel> RetreiveUserAsync(string username, string password) {
            return base.Channel.RetreiveUserAsync(username, password);
        }
        
        public int UpdateUser(string username, string password) {
            return base.Channel.UpdateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(string username, string password) {
            return base.Channel.UpdateUserAsync(username, password);
        }
        
        public int AddGamePlayer(SeniorDBServer.GamePlayerModel player) {
            return base.Channel.AddGamePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> AddGamePlayerAsync(SeniorDBServer.GamePlayerModel player) {
            return base.Channel.AddGamePlayerAsync(player);
        }
        
        public SeniorDBServer.GamePlayerModel[] RetreiveGamePlayers(int gid) {
            return base.Channel.RetreiveGamePlayers(gid);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GamePlayerModel[]> RetreiveGamePlayersAsync(int gid) {
            return base.Channel.RetreiveGamePlayersAsync(gid);
        }
        
        public int[] RetreivePlayerGames(string username) {
            return base.Channel.RetreivePlayerGames(username);
        }
        
        public System.Threading.Tasks.Task<int[]> RetreivePlayerGamesAsync(string username) {
            return base.Channel.RetreivePlayerGamesAsync(username);
        }
        
        public int AddGame(SeniorDBServer.GameModel game) {
            return base.Channel.AddGame(game);
        }
        
        public System.Threading.Tasks.Task<int> AddGameAsync(SeniorDBServer.GameModel game) {
            return base.Channel.AddGameAsync(game);
        }
        
        public int DeleteGame(int gameid) {
            return base.Channel.DeleteGame(gameid);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGameAsync(int gameid) {
            return base.Channel.DeleteGameAsync(gameid);
        }
        
        public SeniorDBServer.GameModel RetreiveGame(int gameid) {
            return base.Channel.RetreiveGame(gameid);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GameModel> RetreiveGameAsync(int gameid) {
            return base.Channel.RetreiveGameAsync(gameid);
        }
        
        public SeniorDBServer.GameModel[] RetreiveAllGames() {
            return base.Channel.RetreiveAllGames();
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GameModel[]> RetreiveAllGamesAsync() {
            return base.Channel.RetreiveAllGamesAsync();
        }
        
        public int UpdateGameNumofPlayers(int gid, int nop) {
            return base.Channel.UpdateGameNumofPlayers(gid, nop);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameNumofPlayersAsync(int gid, int nop) {
            return base.Channel.UpdateGameNumofPlayersAsync(gid, nop);
        }
        
        public SeniorDBServer.GameFrameModel[] GameByNumPlayer(int nop) {
            return base.Channel.GameByNumPlayer(nop);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GameFrameModel[]> GameByNumPlayerAsync(int nop) {
            return base.Channel.GameByNumPlayerAsync(nop);
        }
        
        public int AddGFStrategy(SeniorDBServer.GFStrategyModel gfstrategy) {
            return base.Channel.AddGFStrategy(gfstrategy);
        }
        
        public System.Threading.Tasks.Task<int> AddGFStrategyAsync(SeniorDBServer.GFStrategyModel gfstrategy) {
            return base.Channel.AddGFStrategyAsync(gfstrategy);
        }
        
        public SeniorDBServer.GFStrategyModel RetreiveGFStrategy(int gfstrategyid) {
            return base.Channel.RetreiveGFStrategy(gfstrategyid);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.GFStrategyModel> RetreiveGFStrategyAsync(int gfstrategyid) {
            return base.Channel.RetreiveGFStrategyAsync(gfstrategyid);
        }
        
        public int AddNPStrategy(SeniorDBServer.NPStrategyModel npstrategy) {
            return base.Channel.AddNPStrategy(npstrategy);
        }
        
        public System.Threading.Tasks.Task<int> AddNPStrategyAsync(SeniorDBServer.NPStrategyModel npstrategy) {
            return base.Channel.AddNPStrategyAsync(npstrategy);
        }
        
        public SeniorDBServer.NPStrategyModel RetreiveNPStrategy(int npstrategyid, string username) {
            return base.Channel.RetreiveNPStrategy(npstrategyid, username);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.NPStrategyModel> RetreiveNPStrategyAsync(int npstrategyid, string username) {
            return base.Channel.RetreiveNPStrategyAsync(npstrategyid, username);
        }
        
        public int AddNashPointProfile(SeniorDBServer.NashPointProfileModel NP) {
            return base.Channel.AddNashPointProfile(NP);
        }
        
        public System.Threading.Tasks.Task<int> AddNashPointProfileAsync(SeniorDBServer.NashPointProfileModel NP) {
            return base.Channel.AddNashPointProfileAsync(NP);
        }
        
        public SeniorDBServer.NashPointProfileModel RetreiveNashPointProfile(int NPID) {
            return base.Channel.RetreiveNashPointProfile(NPID);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.NashPointProfileModel> RetreiveNashPointProfileAsync(int NPID) {
            return base.Channel.RetreiveNashPointProfileAsync(NPID);
        }
        
        public int AddNPPayoff(SeniorDBServer.NPPayoffModel payoff) {
            return base.Channel.AddNPPayoff(payoff);
        }
        
        public System.Threading.Tasks.Task<int> AddNPPayoffAsync(SeniorDBServer.NPPayoffModel payoff) {
            return base.Channel.AddNPPayoffAsync(payoff);
        }
        
        public SeniorDBServer.NPPayoffModel RetreiveNPPayoff(int payoffid, string username) {
            return base.Channel.RetreiveNPPayoff(payoffid, username);
        }
        
        public System.Threading.Tasks.Task<SeniorDBServer.NPPayoffModel> RetreiveNPPayoffAsync(int payoffid, string username) {
            return base.Channel.RetreiveNPPayoffAsync(payoffid, username);
        }
    }
}
